### ISSUE TITLE
Add addittional worlds from this repo

### ISSUE THREAD

**Issue by leha-code** [MCPI-Revival/mcpi-repo#22]
https://github.com/raseribanez/Minecraft-Pi-Python-NEW-MAPS
I had problems loading them. Ask alv for more  info

**Comment by mobilegmYT** [comment]
Please make pull request!

**Comment by leha-code** [comment]
I can't! I am having world loading problems. It does nott load, displays a white  inffinite void, then if you reload it generates a world and all shades are broken

**Comment by nobody5050** [comment]
Then there’s no need to add them
