### ISSUE TITLE
Introduce a scripts section?

### ISSUE THREAD

**Issue by leha-code** [MCPI-Revival/mcpi-repo#27]

**Comment by simonafield** [comment]
Perhaps.

**Comment by simonafield** [comment]
would need people to vet the scripts for malware and such before approval.

**Comment by leha-code** [comment]
I can give some from my collection

**Comment by leha-code** [comment]
Also ytubers like me and wallee can upload scripts here. this will increase the popularity of our channels, and mcpi-repo

**Comment by NoozAbooz** [comment]
mcpi-repo is dead
